name: Lint

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml
