name: Tests

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

permissions:
  contents: read

jobs:
  native:
    uses: ./.github/workflows/reusable-native.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  standalone:
    uses: ./.github/workflows/reusable-standalone.yml

  tinygo-candidate:
    uses: ./.github/workflows/reusable-tinygo-candidate.yml
