name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

permissions:
  contents: read

jobs:
  test:
    name: Test Modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23' ]
        module: [
          ".",
          "./function",
          "./http",
          "./kv",
          "./log",
          "./metrics",
          "./sql"
        ]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.sum
      
      - name: Run tests with coverage
        working-directory: ${{ matrix.module }}
        run: make tests
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ${{ matrix.module }}/coverage.out
          flags: unittests
          name: codecov-${{ matrix.module }}
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  # This job ensures that all modules work together correctly
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      
      - name: Verify workspace
        run: go work sync
      
      - name: Run all tests
        run: make tests
